// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ijmppzlakgsplacpeodb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlqbXBwemxha2dzcGxhY3Blb2RiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM2NTAzNDUsImV4cCI6MjA2OTIyNjM0NX0.hRIIu21MHargxnuYE3IZjVgYclVoaw66MOkaRpgLr4c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});